# Generated by Django 5.2.9 on 2026-01-07 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('HR', 'Hr'), ('Reviewer', 'Reviewer'), ('Candidate', 'Candidate'), ('Employee', 'Employee')], default='Candidate', max_length=20),
        ),
    ]
