# Generated by Django 5.2.9 on 2026-01-19 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('HR', 'Hr'), ('Reviewer', 'Reviewer'), ('Candidate', 'Candidate'), ('Client', 'Client')], default='Candidate', max_length=20),
        ),
    ]
