# Generated by Django 5.2.9 on 2026-01-07 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_alter_job_description_text_alter_job_gliner_entities_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='description_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
