# Generated by Django 5.2.9 on 2026-01-19 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('jobs', '0003_alter_job_description_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='clients.clientcompany'),
        ),
        migrations.AddField(
            model_name='job',
            name='commission_rate',
            field=models.DecimalField(decimal_places=2, default=15.0, help_text='Agency Fee % for this specific job', max_digits=5),
        ),
        migrations.AddField(
            model_name='job',
            name='salary_budget',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Annual Salary Budget (for commission calc)', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='processed_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed'), ('FILLED', 'Filled')], default='OPEN', max_length=10),
        ),
    ]
