# Generated by Django 5.2.9 on 2026-01-19 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_job_client_contact_alter_job_posted_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='client_does_final_interview',
            field=models.BooleanField(default=True, help_text='Will the client interview the final shortlist?'),
        ),
        migrations.AddField(
            model_name='job',
            name='exam_link',
            field=models.URLField(blank=True, help_text='Link to the MCQ form (Google Forms/Typeform)', null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='exam_passing_score',
            field=models.IntegerField(default=60, help_text='Score % required to pass'),
        ),
        migrations.AddField(
            model_name='job',
            name='has_primary_exam',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='target_candidates_count',
            field=models.IntegerField(default=1, help_text='How many candidates the client wants'),
        ),
    ]
