# Generated by Django 5.2.9 on 2026-01-20 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_remove_job_exam_link_alter_job_status_examattempt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='joining_date',
            field=models.DateField(blank=True, help_text='Expected Joining Date', null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='monthly_salary',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monthly Salary offered to the candidate per person', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='commission_rate',
            field=models.DecimalField(decimal_places=2, default=20.0, help_text='Agency Fee % for this specific job (Dynamic)', max_digits=5),
        ),
        migrations.AlterField(
            model_name='job',
            name='salary_budget',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Annual Salary Budget (Optional/Legacy)', max_digits=12, null=True),
        ),
    ]
