# Generated by Django 5.2.9 on 2026-01-23 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_job_joining_date_job_monthly_salary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='office_location',
            field=models.CharField(blank=True, help_text='Office Location (e.g. Dhaka, Remote)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='salary_max',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum Monthly Salary', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='salary_min',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Minimum Monthly Salary', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='monthly_salary',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monthly Salary offered to the candidate per person (or Avg of Range)', max_digits=10, null=True),
        ),
    ]
