# Generated by Django 5.2.9 on 2026-01-19 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Google, Acme Corp', max_length=255, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='client_logos/')),
                ('industry', models.CharField(blank=True, help_text='e.g. Fintech, Healthcare', max_length=100)),
                ('website', models.URLField(blank=True)),
                ('contact_person', models.CharField(help_text='Who do we send CVs to?', max_length=255)),
                ('email', models.EmailField(help_text='Contact email for invoicing and updates', max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('contract_status', models.CharField(choices=[('Active', 'Active'), ('Suspended', 'Suspended'), ('Pending', 'Pending')], default='Active', max_length=20)),
                ('default_commission', models.DecimalField(decimal_places=2, default=15.0, help_text='Default Agency Fee (%)', max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Client Companies',
            },
        ),
    ]
