# Generated by Django 5.2.9 on 2026-01-07 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('APPLIED', 'Applied'), ('SHORTLISTED', 'Shortlisted for Interview'), ('REJECTED', 'Rejected')], default='APPLIED', max_length=20),
        ),
    ]
