# Generated by Django 5.2.9 on 2026-01-19 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0003_alter_application_cv_embedding_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('APPLIED', 'New Applied'), ('SCREENING', 'Screening'), ('INTERVIEW', 'Interview'), ('CLIENT_REVIEW', 'Shared with Client'), ('OFFER', 'Offer Sent'), ('HIRED', 'Hired'), ('REJECTED', 'Rejected')], default='APPLIED', max_length=20),
        ),
    ]
