# Generated by Django 5.2.9 on 2026-01-20 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0006_application_assigned_reviewer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('PENDING_EXAM', 'Pending Exam'), ('APPLIED', 'New Applied'), ('SCREENING', 'Screening'), ('INTERVIEW', 'Internal Interview'), ('CLIENT_REVIEW', 'Shared with Client'), ('FINAL_INTERVIEW', 'Final Interview'), ('OFFER', 'Offer Sent'), ('HIRED', 'Hired'), ('REJECTED', 'Rejected')], default='APPLIED', max_length=20),
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.DecimalField(decimal_places=2, help_text='Monthly or Yearly Salary', max_digits=10)),
                ('start_date', models.DateField()),
                ('benefits', models.TextField(blank=True, help_text='List of benefits (Health, Remote, etc.)')),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Decision'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='offer_letter', to='candidates.application')),
            ],
        ),
    ]
