# Generated by Django 5.2.9 on 2026-01-20 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0009_alter_application_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('PENDING_EXAM', 'Pending Exam'), ('APPLIED', 'Applied'), ('INTERVIEW', 'Internal Interview'), ('CLIENT_REVIEW', 'Client Review'), ('FINAL_INTERVIEW', 'Final Interview'), ('OFFER', 'Offer Sent'), ('HIRED', 'Hired'), ('REJECTED', 'Rejected')], default='APPLIED', max_length=20),
        ),
    ]
