# Generated by Django 5.2.9 on 2026-01-20 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0010_alter_application_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='interview_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='interview_note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
