# Generated by Django 5.2.9 on 2026-01-20 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0011_application_interview_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='offer_message',
            field=models.TextField(blank=True, help_text='Personal note or official terms', null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='offer_salary',
            field=models.CharField(blank=True, help_text='e.g. $5,000/month', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='offer_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
