# Generated by Django 5.2.9 on 2026-01-23 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0012_application_offer_message_application_offer_salary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='candidate_expected_salary',
            field=models.CharField(blank=True, help_text="Candidate's expected salary input", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='candidate_joining_date',
            field=models.DateField(blank=True, help_text="Candidate's expected joining date", null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('PENDING_EXAM', 'Pending Exam'), ('APPLIED', 'Applied'), ('INTERVIEW', 'Internal Interview'), ('CLIENT_REVIEW', 'Client Review'), ('FINAL_INTERVIEW', 'Final Interview'), ('NEGOTIATION', 'Salary Negotiation'), ('NEGOTIATION_SUBMITTED', 'Negotiation Submitted'), ('OFFER', 'Offer Sent'), ('HIRED', 'Hired'), ('REJECTED', 'Rejected')], default='APPLIED', max_length=50),
        ),
    ]
